Add job `ci is happy` to check is other jobs where successful
Other Changes
-------------

- Remove job `Quality` since it's already done in `linux-check-test-build`.
- Rename `linux-build` to `linux-check-test-build`.
- Also rename the job `windows-packaging`.
- Add spacing between steps.

Closes #128

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,38 +16,61 @@ env:
 
 jobs:
 
-
-#################################################################################
-
-  Quality:
+    # Github PR merging is configured to only require this job to pass
+  ci-is-happy:
+    name: ⭐ CI is happy ⭐
+    needs:
+      - linux-check-test-build
+      - windows-build
+      - windows-packaging
     runs-on: ubuntu-latest
+    if: always()
+    # Just a fail-safe timeout, see the fine grain per-task timeout instead
+    timeout-minutes: 2
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v4
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-      - uses: pre-commit/action@v3.0.0
+      # The Needs context value contains only:
+      # - the final state a jobs (if it fails or not)
+      # - it's output (actually none of our jobs are configuring outputs variable)
+      #
+      # https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
+      - name: Debug the needs context values
         env:
-          SKIP: mypy-client
+          NEEDS: ${{ toJSON(needs) }}
+        run: printenv NEEDS
 
+      - name: We're very sorry
+        run: |
+          echo "Oh No, we have jobs that have failed/cancelled/skipped :("
+          exit 21
+        if: >-
+          contains(needs.*.result, 'failure')
+          || contains(needs.*.result, 'skipped')
+          || contains(needs.*.result, 'cancelled')
+          || ! contains(needs.*.result, 'success')
+
+      - name: It's showtime
+        run: echo "My job here is done !"
 
 #################################################################################
 
 
-  linux-build:
-    name: '🐧 Linux build'
+  linux-check-test-build:
+    name: '🐧 Linux check, test & build'
     runs-on: ubuntu-latest
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v3 # pin@v3.0.2
         with:
             submodules: true
+
       - name: 'Set up Python'
         uses: actions/setup-python@v4  # pin@v4.0.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
+
       - name: 'Install fuse'
         run: sudo apt-get install -y libfuse2
+
       - name: 'Install tools'
         working-directory: client
         run: |
@@ -56,23 +79,29 @@ jobs:
           python -m pip install --user pipx
           pipx install poetry
           poetry --version
+
       - name: '[Client] Install Project'
         run: poetry install -v
         working-directory: client
+
       - name: '[Client] Check fuse'
         run: poetry run python -c "import fuse"
         working-directory: client
+
       - name: '[Client] Run Tests'
         run: poetry run py.test client_tests
         timeout-minutes: 10
         working-directory: client
+
       - name: '[Server] Install Project'
         run: poetry install -v
         working-directory: server
+
       - name: '[Server] Run Tests'
         run: poetry run py.test server_tests
         timeout-minutes: 10
         working-directory: server
+
       - name: '[Quality] Run pre-commit with mypy-client'
         uses: pre-commit/action@v3.0.0
 
@@ -88,10 +117,12 @@ jobs:
         uses: actions/checkout@v3 # pin@v3.0.2
         with:
             submodules: true
+
       - name: 'Set up Python'
         uses: actions/setup-python@v4  # pin@v4.0.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
+
       - name: 'Setup env'
         shell: bash
         run: |
@@ -101,15 +132,18 @@ jobs:
           pipx install poetry
           poetry --version
         working-directory: client
+
       - name: 'Install WinFSP'
         shell: bash
         run: |
           set -eux
           choco install -y --limit-output winfsp --version=${{ env.WINFSP_VERSION }}
         working-directory: client
+
       - name: 'Install project'
         run: poetry install -v
         working-directory: client
+
       - name: 'Run tests'
         run: poetry run py.test client_tests
         timeout-minutes: 10
@@ -119,7 +153,7 @@ jobs:
 #################################################################################
 
 
-  windows-packing:
+  windows-packaging:
     name: '🏁 Windows packaging'
     runs-on: windows-latest
     steps:
@@ -127,10 +161,12 @@ jobs:
         uses: actions/checkout@v3 # pin@v3.0.2
         with:
             submodules: true
+
       - name: 'Set up Python'
         uses: actions/setup-python@v4  # pin@v4.0.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
+
       - name: 'Setup env'
         shell: bash
         run: |
@@ -140,9 +176,11 @@ jobs:
           pipx install poetry
           poetry --version
         working-directory: client
+
       - name: Freeze Parsec
         run: python freeze_program.py ../../client
         working-directory: packaging/windows/
+
       - name: 'Upload installer as artifact'
         uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin v3.1.2
         with:
